### PR TITLE
Revert these changes to the UI and just always insert after.

### PR DESCRIPTION
**Pull request by jeffeb3**
Kinda weird PR. But I didn't want to create too much work for this. I just reverted most of that topic and pushed it here. This was tested locally. Seems good to me.

### CODE REVIEW

**Comment by jeffeb3** [comment]
Looks like I have to fix a test.

It also doesn't seem to be inserting in the right place for a copy.

**Comment by jeffeb3** [comment]
The test isn't really fixed. I just gave it what it wants to pass. I think we would need to set the state of the current selected layer for it to insert it in the right place.

**Comment by jeffeb3** [comment]
If I do something like this:
 - Make two layers
 - Select the first
 - Hit the copy button on the second
I was hoping it would copy it to after the first. But instead, hitting the copy button causes it to select the second layer, and it always adds it after the one it was copied from.

AFAICT, it does this on both branches.

I guess we would need to keep the value of the copied layer separate from the most recently selected layer. And then, is it tricky to get the copy button to not select a new layer?

**Comment by jeffeb3** [comment]
If the copy thing is hard to fix, I am still ok moving forward (I am hoping to release soon)(.

**Comment by bobnik** [comment]
> If the copy thing is hard to fix, I am still ok moving forward (I am hoping to release soon)(.

I completely missed this PR to my PR and submitted a new one for your review. I think we did the same thing code-wise. Sorry about that.

**Comment by jeffeb3** [comment]
No problem. It wasn't much code.

**Pull request closed without merging**
